sample.value=local\uc11c\ubc84
server.port=8080
server.servlet.context-path=/

spring.config.activate.on-profile:local

# servlet-context.xml
spring.mvc.view.prefix=/WEB-INF/views
spring.mvc.view.suffix=.jsp

# UTF-8 \uc778\ucf54\ub529 \uc124\uc815
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# \ud504\ub85c\ud544\uc774 \uc544\ub2cc main properties\uc5d0\ub9cc \uc124\uc815\ud574\ub450\uc5b4\uc57c \ud55c\ub2e4.
# spring \ud504\ub85c\ud30c\uc77c \uc124\uc815(local, dev, prod)
# spring.profiles.active=local

# 0917_\ucca8\ubd80\ud30c\uc77c \uae30\ub2a5\uc744 \uc704\ud55c Multipart \uc124\uc815 \ub4f1\ub85d
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=100MB

# SecurityFilter\ub294 SecurityConfig\ub85c \uc885\uacb0
# *-context.xml\uc744 \ubd88\ub7ec\uc624\ub294 \uac74 Bean\ub4f1\ub85d\uc73c\ub85c \ud574\uacb0
# dispatcherServlet\uc774\ub098 Listener\ub294 Boot\uc5d0\uac8c \uc77c\uc784



# DataSource datasource\ub9cc \uc798 \ub9cc\ub4e4\uc5b4\ub123\uc73c\uba74 SqlSession Factory & Template\uc744 \uc54c\uc544\uc11c Boot\uac00 \ub9cc\ub4e0\ub2e4.
spring.datasource.driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:mariadb://localhost:23306/mydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=letech
spring.datasource.password=letech

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mybatis/**/*.xml
# mybatis.config-location=classpath:/config/mybatis/

# MessageSource
spring.messages.basename=message/message-common
spring.messages.cache-duration=60s
spring.message.encoding=UTF-8
spring.messages.fallback-to-system-locale=false



file.storage.dir=D:/java/eclipse/eGovFrameDev-4.0.0-64bit/eclipse/study.SpringMVC